const KEY='rpg-life-v3';
const today=()=>new Date().toISOString().slice(0,10);
const uid=()=>crypto.randomUUID?.()||Math.random().toString(36).slice(2);
const clamp=(n,a=0,b=100)=>Math.max(a,Math.min(b,n));
const pct=(a,b)=>b?clamp(Math.round((Number(a)||0)/Number(b)*100)):0;
const fmt=d=>new Intl.DateTimeFormat('ru-RU',{day:'numeric',month:'short',year:'numeric'}).format(new Date(d+'T12:00:00'));
const branchMeta={health:{name:'Здоровье',icon:'✚'},presence:{name:'Присутствие',icon:'✦'},work:{name:'Работа',icon:'⚒'},creative:{name:'Творчество',icon:'✒'},study:{name:'Обучение',icon:'⌁'},publicity:{name:'Публичность',icon:'◉'},infrastructure:{name:'Инфраструктура',icon:'⌂'}};

function fresh(){return {
  wallet:{gold:0,diamonds:0},
  practices:[
    {id:'train',name:'Тренировка',branches:{health:25},rhythm:{type:'timesWeek',value:5},metrics:[]},
    {id:'hof',name:'Хоф + отжимания',branches:{health:20},rhythm:{type:'timesWeek',value:5},metrics:['Задержка, сек','Отжимания']},
    {id:'cold',name:'Закаливание',branches:{health:15},rhythm:{type:'timesWeek',value:5},metrics:['Холод, сек']},
    {id:'steps',name:'Шаги',branches:{health:30},rhythm:{type:'weeklyAmount',value:60000,unit:'шагов'},metrics:['Шагов']},
    {id:'revitonica',name:'Ревитоника',branches:{health:10,presence:30},rhythm:{type:'timesWeek',value:4},metrics:[]},
    {id:'spf',name:'SPF',branches:{presence:18},rhythm:{type:'daily'},metrics:[]},
    {id:'nizoral',name:'Низорал',branches:{presence:12},rhythm:{type:'everyDays',value:14},metrics:[]},
    {id:'calligraphy',name:'Каллиграфия',branches:{creative:8},rhythm:{type:'soft'},metrics:[],effects:['Вдохновение']},
    {id:'journal',name:'Дневник',branches:{creative:6},rhythm:{type:'soft'},metrics:[],effects:['Вдохновение']}
  ],
  practiceLogs:[],
  states:[{id:uid(),type:'buff',title:'Чистая полоса',note:'Без алкоголя. Длинный ритм может приносить алмазы.',strength:null}],
  bosses:[{id:'contract251',title:'Муниципальный контракт 251',rank:'epic',deadline:'2026-09-30',targetDate:null,price:892639.20,stages:[{id:'scan',name:'Сканирование',kind:'fixed',total:28888,done:2000,unit:'листов'},{id:'process',name:'Обработка',kind:'fixed',total:28888,done:null,unit:'листов'},{id:'cards',name:'Карточки и загрузка в ГИС',kind:'unknown',done:0,unit:'карточек'}],final:[{id:'ssd-buy',label:'Купить 3 SSD',done:false},{id:'ssd-write',label:'Записать 3 комплекта массива',done:false},{id:'transfer',label:'Передать носители заказчику',done:false},{id:'docs',label:'Сформировать финальные документы и отчёты',done:false}],reward:'Назначить большую награду за убийство босса'}],
  campaigns:[{id:'calbank',title:'Банк дефицита · −10 кг',total:70000,done:2000,unit:'ккал'}],
  rewards:[{id:uid(),title:'Вкусняшка',currency:'gold',price:120},{id:uid(),title:'Кафешка',currency:'gold',price:300},{id:uid(),title:'Новая игра',currency:'diamonds',price:3},{id:uid(),title:'День анархии',currency:'diamonds',price:5}],
  achievements:[{id:uid(),date:'2026-08-07',title:'Релиз «Гранитной кожи»',tier:'epic'}],
  journal:[]
}}
let state=(()=>{try{return JSON.parse(localStorage.getItem(KEY))||fresh()}catch{return fresh()}})();
let view='today',selectedDate=today();
const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function rhythmLabel(r){if(!r)return'без ритма';if(r.type==='timesWeek')return`${r.value}× в неделю`;if(r.type==='weeklyAmount')return`${Number(r.value).toLocaleString('ru-RU')} ${r.unit||''}/нед`;if(r.type==='daily')return'ежедневно';if(r.type==='everyDays')return`раз в ${r.value} дней`;return'мягкий ритм';}
function weekStart(date){const d=new Date(date+'T12:00:00');const day=(d.getDay()+6)%7;d.setDate(d.getDate()-day);return d;}
function iso(d){return d.toISOString().slice(0,10)}
function weekDates(date){const s=weekStart(date);return Array.from({length:7},(_,i)=>{const d=new Date(s);d.setDate(d.getDate()+i);return iso(d)})}
function logsForDate(date){return state.practiceLogs.filter(x=>x.date===date)}
function branchPractices(k){return state.practices.filter(p=>Number(p.branches?.[k])>0)}
function daysLeft(date){return Math.ceil((new Date(date+'T23:59:59')-new Date())/86400000)}
function bossThreat(b){const d=daysLeft(b.deadline),fixed=b.stages.filter(s=>s.kind==='fixed'&&s.done!==null);const prog=fixed.length?fixed.reduce((n,s)=>n+pct(s.done,s.total),0)/fixed.length:0;if(d<0)return'ФАТАЛИТИ';if(d<=7&&prog<85)return'ярость';if(d<=20&&prog<60)return'агрессивен';return'контролируем';}

function render(){document.querySelectorAll('[data-nav]').forEach(x=>x.classList.toggle('active',x.dataset.nav===view));document.querySelector('#app').innerHTML=({today:todayView,branches:branchesView,battles:battlesView,rewards:rewardsView,memory:memoryView,year:yearView}[view]||todayView)();bind();}
function dayStrip(){const names=['Пн','Вт','Ср','Чт','Пт','Сб','Вс'];return `<div class="day-strip">${weekDates(selectedDate).map((d,i)=>{const n=new Date(d+'T12:00:00').getDate();const count=logsForDate(d).length;return `<button class="day-pill ${d===selectedDate?'selected':''} ${d===today()?'today':''}" data-date="${d}"><small>${names[i]}</small><b>${n}</b>${count?`<i>${count}</i>`:''}</button>`}).join('')}</div>`}
function branchMenus(){return `<div class="activity-menus">${Object.entries(branchMeta).map(([k,m])=>{const ps=branchPractices(k);return `<details class="activity-menu"><summary><span>${m.icon}</span><b>${m.name}</b><small>${ps.length} практик</small></summary><div class="activity-menu-body">${ps.length?ps.map(p=>`<div class="activity-option"><button class="activity-log" data-practice="${p.id}"><b>${esc(p.name)}</b><small>${rhythmLabel(p.rhythm)}</small></button><button class="activity-edit" data-edit-practice="${p.id}" title="Настроить">⚙</button></div>`).join(''):'<div class="empty-v2">Пока практик нет.</div>'}<button class="add-inside" data-add-practice="${k}">＋ добавить практику</button></div></details>`}).join('')}</div>`}
function rhythmCard(){const dates=weekDates(selectedDate);const rows=state.practices.filter(p=>p.rhythm?.type!=='soft').map(p=>{const logs=state.practiceLogs.filter(l=>dates.includes(l.date)&&l.practiceId===p.id);let value='';if(p.rhythm.type==='weeklyAmount'){const sum=logs.reduce((n,l)=>n+(Number(l.amount)||0),0);value=`${sum.toLocaleString('ru-RU')} / ${Number(p.rhythm.value).toLocaleString('ru-RU')} ${p.rhythm.unit||''}`;}else if(p.rhythm.type==='timesWeek')value=`${new Set(logs.map(l=>l.date)).size} / ${p.rhythm.value}`;else if(p.rhythm.type==='daily')value=`${new Set(logs.map(l=>l.date)).size} / 7`;else if(p.rhythm.type==='everyDays'){const last=[...state.practiceLogs].filter(l=>l.practiceId===p.id&&l.date<=selectedDate).sort((a,b)=>b.date.localeCompare(a.date))[0];value=last?`последний раз ${fmt(last.date)}`:`ещё не отмечено`;}return `<div class="rhythm-row"><div><b>${esc(p.name)}</b><small>${rhythmLabel(p.rhythm)}</small></div><strong>${value}</strong></div>`}).join('');return rows||'<div class="empty-v2">Ритмы появятся после добавления практик.</div>'}
function todayLog(){const logs=logsForDate(selectedDate);if(!logs.length)return'<div class="empty-v2">Этот день пока не описан. Это не означает, что он пустой.</div>';return logs.map(l=>{const p=state.practices.find(x=>x.id===l.practiceId);const details=l.metrics?Object.entries(l.metrics).map(([k,v])=>`${esc(k)}: ${esc(v)}`).join(' · '):'';return `<div class="today-event"><span>${branchMeta[Object.keys(p?.branches||{})[0]]?.icon||'•'}</span><div><b>${esc(p?.name||'Практика')}</b><small>${details||((l.amount!==undefined&&l.amount!==null)?esc(l.amount):'отмечено')}</small></div></div>`}).join('')}
function todayView(){const c=state.campaigns[0];return `<div class="v2-wrap"><section class="v2-grid"><article class="v2-card v2-span-12"><div class="v2-row"><div><div class="v2-kicker">День персонажа</div><h1 class="v2-title">${fmt(selectedDate)}</h1></div><div class="currency-bar"><div class="currency-pill gold">🪙 <b>${state.wallet.gold}</b></div><div class="currency-pill diamond">💎 <b>${state.wallet.diamonds}</b></div></div></div>${dayStrip()}</article><article class="v2-card v2-span-8"><div class="v2-kicker">Быстрая фиксация</div><h2 class="v2-title">Что произошло?</h2><div class="v2-sub">Выбери область жизни, затем практику. Недельная частота здесь не является списком обязанностей.</div>${branchMenus()}</article><article class="v2-card v2-span-4"><div class="v2-kicker">Зафиксировано</div><h3 class="v2-title">Этот день</h3><div class="today-log">${todayLog()}</div></article><article class="v2-card v2-span-7"><div class="v2-kicker">Ритм</div><h3 class="v2-title">Неделя вокруг выбранного дня</h3><div class="rhythm-list">${rhythmCard()}</div></article><article class="v2-card v2-span-5"><div class="v2-kicker">Состояние мира</div><h3 class="v2-title">Бафы и дебафы</h3><div class="state-stack">${state.states.map(s=>`<div class="state-chip ${s.type}"><b>${s.type==='buff'?'✦':'⚠'} ${esc(s.title)}</b><small>${esc(s.note||'')}${s.strength?` · сила ${s.strength}/10`:''}</small></div>`).join('')||'<div class="empty-v2">Сейчас ничего активного.</div>'}</div><button class="ghost" id="addState" style="margin-top:10px">＋ состояние</button></article><article class="v2-card v2-span-6"><div class="v2-kicker">Сквозная кампания</div><h3 class="v2-title">${esc(c.title)}</h3><div class="v2-row"><b>${c.done.toLocaleString('ru-RU')} / ${c.total.toLocaleString('ru-RU')}</b><span>${pct(c.done,c.total)}%</span></div><div class="bar green"><i style="width:${pct(c.done,c.total)}%"></i></div><div class="v2-sub" style="margin-top:7px">Осталось ${(c.total-c.done).toLocaleString('ru-RU')} ${c.unit}</div></article><article class="v2-card v2-span-6"><div class="v2-kicker">Битвы</div><h3 class="v2-title">Активные противники</h3>${state.bosses.map(b=>`<div class="arch-note"><b>${esc(b.title)}</b> · эпический · ${bossThreat(b)}</div>`).join('')}<button class="soft" data-go="battles" style="margin-top:10px">Открыть арену →</button></article></section></div>`}

function branchesView(){return `<div class="v2-wrap"><div class="v2-kicker">Ветки жизни</div><h1 class="v2-title">Практики и их влияние</h1><div class="v2-sub">Вес — твоя собственная оценка того, насколько практика поддерживает эту ветку. Его можно менять в любой момент.</div><div class="branch-list" style="margin-top:14px">${Object.entries(branchMeta).map(([k,m])=>`<article class="branch-tile"><header><div><h3>${m.icon} ${m.name}</h3><div class="v2-sub">${branchPractices(k).length} практик</div></div><button class="soft" data-add-practice="${k}">＋</button></header><div class="practice-tags">${branchPractices(k).map(p=>`<button class="practice-tag editable" data-edit-practice="${p.id}">${esc(p.name)} · влияние ${p.branches[k]} · ${rhythmLabel(p.rhythm)}</button>`).join('')||'<span class="practice-tag">пока пусто</span>'}</div></article>`).join('')}</div></div>`}
function battlesView(){return `<div class="v2-wrap"><div class="v2-kicker">Арена</div><h1 class="v2-title">Боссы и враги</h1><div class="v2-grid">${state.bosses.map(b=>bossHTML(b)).join('')}</div></div>`}
function bossHTML(b){return `<article class="v2-card v2-span-12 boss-card ${b.rank}"><div class="boss-head"><div><div class="v2-kicker">Эпический босс</div><h2 class="v2-title">${esc(b.title)}</h2><div class="v2-sub">${Math.round(b.price).toLocaleString('ru-RU')} ₽</div></div><span class="rank">${b.rank}</span></div><div class="boss-meta"><span>☠ ${fmt(b.deadline)}</span><span>⏳ ${daysLeft(b.deadline)} дней</span><span>⚔ ${bossThreat(b)}</span></div>${b.stages.map(s=>s.kind==='unknown'?`<div class="stage"><div class="unknown"><b>🌫 ${esc(s.name)} — неизведанная фаза</b><div class="stage-input"><input type="number" min="0" value="${s.done||0}" data-boss-stage="${b.id}:${s.id}"><small>${s.unit}</small></div></div></div>`:`<div class="stage"><div class="stage-line"><b>${esc(s.name)}</b><span>${s.done===null?'не внесено':`${s.done.toLocaleString('ru-RU')} / ${s.total.toLocaleString('ru-RU')} ${s.unit}`}</span></div><div class="bar"><i style="width:${s.done===null?0:pct(s.done,s.total)}%"></i></div><div class="stage-input"><input type="number" min="0" max="${s.total}" value="${s.done??''}" data-boss-stage="${b.id}:${s.id}"></div></div>`).join('')}<div class="stage"><div class="v2-kicker">Финальная фаза · фаталити</div><div class="final-list">${b.final.map(x=>`<label><input type="checkbox" data-final="${b.id}:${x.id}" ${x.done?'checked':''}> ${esc(x.label)}</label>`).join('')}</div></div><div class="legendary-note"><b>Награда:</b> ${esc(b.reward)}</div></article>`}
function rewardsView(){return `<div class="v2-wrap"><div class="v2-row"><div><div class="v2-kicker">Экономика</div><h1 class="v2-title">Сокровищница</h1></div><div class="currency-bar"><div class="currency-pill gold">🪙 <b>${state.wallet.gold}</b></div><div class="currency-pill diamond">💎 <b>${state.wallet.diamonds}</b></div></div></div><div class="v2-card"><div class="reward-grid">${state.rewards.map(r=>`<div class="reward"><b>${esc(r.title)}</b><div class="v2-row"><span>${r.price} ${r.currency==='gold'?'🪙':'💎'}</span><button class="soft" data-buy="${r.id}">Купить</button></div></div>`).join('')}</div></div></div>`}
function memoryView(){return `<div class="v2-wrap"><div class="v2-kicker">Память персонажа</div><h1 class="v2-title">Достижения не исчезают</h1><div class="v2-card">${state.achievements.map(a=>`<div class="legendary-note"><b>${fmt(a.date)} · ${esc(a.title)}</b></div>`).join('')}</div></div>`}
function monthHTML(year,month){const first=new Date(year,month,1),days=new Date(year,month+1,0).getDate(),offset=(first.getDay()+6)%7,names=['Пн','Вт','Ср','Чт','Пт','Сб','Вс'];let cells='<div class="month-weekdays">'+names.map(x=>`<small>${x}</small>`).join('')+'</div><div class="month-days">'+Array.from({length:offset},()=>'<span></span>').join('');for(let d=1;d<=days;d++){const date=`${year}-${String(month+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`,ach=state.achievements.find(a=>a.date===date),n=logsForDate(date).length;cells+=`<button data-calendar-date="${date}" class="calendar-day ${ach?.tier||''} ${date===selectedDate?'selected':''}"><b>${d}</b>${n?`<i>${n}</i>`:''}</button>`}return `<article class="month-card"><h3>${new Intl.DateTimeFormat('ru-RU',{month:'long'}).format(first)}</h3>${cells}</div></article>`}
function yearView(){const y=new Date().getFullYear();return `<div class="v2-wrap"><div class="v2-kicker">Карта года · ${y}</div><h1 class="v2-title">Год по месяцам</h1><div class="months-grid">${Array.from({length:12},(_,m)=>monthHTML(y,m)).join('')}</div><div class="v2-card calendar-detail"><div class="v2-kicker">${fmt(selectedDate)}</div><h3 class="v2-title">Что было в этот день</h3>${todayLog()}</div></div>`}

function openModal(html){const m=document.querySelector('#modal');m.innerHTML=`<div class="modal-inner">${html}</div>`;m.showModal();m.querySelector('.close')?.addEventListener('click',()=>m.close())}
function practiceForm(p={},primaryBranch='health'){const branches=p.branches||{[primaryBranch]:10};const r=p.rhythm||{type:'timesWeek',value:1};return `<div class="modal-head"><div><div class="v2-kicker">Практика</div><h2>${p.id?'Настроить':'Добавить'}</h2></div><button class="close">×</button></div><form id="practiceForm"><input type="hidden" name="id" value="${p.id||''}"><label>Название<input name="name" required value="${esc(p.name||'')}"></label><div class="form-section"><b>Влияние на ветки</b><small>0 — практика не связана с веткой. 100 — очень большой вклад.</small>${Object.entries(branchMeta).map(([k,m])=>`<div class="weight-row"><span>${m.icon} ${m.name}</span><input type="number" min="0" max="100" name="weight_${k}" value="${branches[k]||0}"></div>`).join('')}</div><label>Желательный ритм<select name="rhythmType"><option value="timesWeek" ${r.type==='timesWeek'?'selected':''}>N раз в неделю</option><option value="weeklyAmount" ${r.type==='weeklyAmount'?'selected':''}>Количество за неделю</option><option value="daily" ${r.type==='daily'?'selected':''}>Ежедневно</option><option value="everyDays" ${r.type==='everyDays'?'selected':''}>Раз в N дней</option><option value="soft" ${r.type==='soft'?'selected':''}>Без жёсткой частоты</option></select></label><div class="form-grid"><label>Число<input name="rhythmValue" type="number" min="0" value="${r.value??''}"></label><label>Единица<input name="unit" value="${esc(r.unit||'')}"></label></div><label>Измеряемые показатели<input name="metrics" value="${esc((p.metrics||[]).join(', '))}" placeholder="например: Задержка, сек; Отжимания"></label><button class="primary" type="submit">Сохранить практику</button></form>`}
function openPracticeEditor(id,branch){const p=id?state.practices.find(x=>x.id===id):null;openModal(practiceForm(p||{},branch));document.querySelector('#practiceForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget),old=p||{id:uid()},branches={};Object.keys(branchMeta).forEach(k=>{const v=Number(f.get('weight_'+k))||0;if(v>0)branches[k]=clamp(v)});const type=f.get('rhythmType'),val=Number(f.get('rhythmValue'))||null;const rhythm={type};if(type==='timesWeek'||type==='everyDays')rhythm.value=val||1;if(type==='weeklyAmount'){rhythm.value=val||1;rhythm.unit=f.get('unit')||'ед.'}const metrics=String(f.get('metrics')||'').split(/[;,]/).map(x=>x.trim()).filter(Boolean);Object.assign(old,{name:f.get('name'),branches,rhythm,metrics});if(!p)state.practices.push(old);save();document.querySelector('#modal').close();render()}}
function logPractice(id){const p=state.practices.find(x=>x.id===id);if(!p)return;const metrics=p.metrics||[];if(!metrics.length){state.practiceLogs.push({id:uid(),practiceId:id,date:selectedDate});save();render();return}openModal(`<div class="modal-head"><div><div class="v2-kicker">${fmt(selectedDate)}</div><h2>${esc(p.name)}</h2></div><button class="close">×</button></div><form id="logForm">${metrics.map((m,i)=>`<label>${esc(m)}<input type="number" step="0.1" name="m${i}" required></label>`).join('')}<button class="primary">Записать</button></form>`);document.querySelector('#logForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget),vals={};metrics.forEach((m,i)=>vals[m]=Number(f.get('m'+i)));const amount=p.rhythm?.type==='weeklyAmount'?Number(f.get('m0')):null;state.practiceLogs.push({id:uid(),practiceId:id,date:selectedDate,metrics:vals,amount});save();document.querySelector('#modal').close();render()}}
function addState(){openModal(`<div class="modal-head"><h2>Состояние</h2><button class="close">×</button></div><form id="stateForm"><label>Тип<select name="type"><option value="buff">Баф</option><option value="debuff">Дебаф</option></select></label><label>Название<input name="title" required></label><label>Сила дебафа 1–10<input name="strength" type="number" min="1" max="10"></label><label>Комментарий<input name="note"></label><button class="primary">Добавить</button></form>`);document.querySelector('#stateForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget);state.states.push({id:uid(),type:f.get('type'),title:f.get('title'),strength:Number(f.get('strength'))||null,note:f.get('note')});save();document.querySelector('#modal').close();render()}}
function bind(){document.querySelectorAll('[data-date]').forEach(b=>b.onclick=()=>{selectedDate=b.dataset.date;render()});document.querySelectorAll('[data-calendar-date]').forEach(b=>b.onclick=()=>{selectedDate=b.dataset.calendarDate;render()});document.querySelectorAll('[data-practice]').forEach(b=>b.onclick=()=>logPractice(b.dataset.practice));document.querySelectorAll('[data-edit-practice]').forEach(b=>b.onclick=()=>openPracticeEditor(b.dataset.editPractice));document.querySelectorAll('[data-add-practice]').forEach(b=>b.onclick=()=>openPracticeEditor(null,b.dataset.addPractice));document.querySelector('#addState')?.addEventListener('click',addState);document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{view=b.dataset.go;render()});document.querySelectorAll('[data-boss-stage]').forEach(i=>i.onchange=()=>{const[bid,sid]=i.dataset.bossStage.split(':'),s=state.bosses.find(b=>b.id===bid)?.stages.find(x=>x.id===sid);if(s){s.done=Math.max(0,Number(i.value)||0);save();render()}});document.querySelectorAll('[data-final]').forEach(i=>i.onchange=()=>{const[bid,fid]=i.dataset.final.split(':'),f=state.bosses.find(b=>b.id===bid)?.final.find(x=>x.id===fid);if(f){f.done=i.checked;save()}})}
document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>{view=b.dataset.nav;render()});document.querySelector('#quickAddBtn')?.addEventListener('click',()=>{view='today';render();document.querySelector('.activity-menus')?.scrollIntoView({behavior:'smooth'})});render();