// RPG Life v10 — boss microtasks, currency rewards, golden prize, robust currency icons
(function(){
  const localISO=()=>{const d=new Date(),y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`};
  const rankLabel=r=>({gray:'Серый',green:'Зелёный',blue:'Синий',purple:'Фиолетовый',gold:'Золотой',epic:'Фиолетовый'})[r]||r||'Без ранга';
  (state.bosses||[]).forEach(b=>{b.microtasks=b.microtasks||[];b.rewardGold=Number(b.rewardGold||0);b.rewardDiamonds=Number(b.rewardDiamonds||0);b.goldenPrize=b.goldenPrize||'';});
  save();

  const coinIcon=()=>'<span class="currency-icon coin-icon" aria-label="золото">G</span>';
  const diamondIcon=()=>'<span class="currency-icon diamond-icon" aria-label="алмазы">D</span>';
  const rewardSummary=b=>{const p=[];if(Number(b.rewardGold||0))p.push(`${Number(b.rewardGold)} золота`);if(Number(b.rewardDiamonds||0))p.push(`${Number(b.rewardDiamonds)} алмазов`);return p.join(' + ')};
  const numericReady=b=>(b.stages||[]).every(s=>s.kind==='unknown'||s.total===null||Number(s.done||0)>=Number(s.total||0));
  const microReady=b=>!(b.microtasks||[]).length||(b.microtasks||[]).every(x=>x.done);
  const finalReady=b=>!(b.final||[]).length||(b.final||[]).every(x=>x.done);
  const hasWork=b=>(b.stages||[]).length||(b.microtasks||[]).length||(b.final||[]).length;
  const victoryReady=b=>!!hasWork(b)&&numericReady(b)&&microReady(b)&&finalReady(b)&&!b.victoryConfirmed;

  function numericHTML(b){if(!(b.stages||[]).length)return'';return `<div class="boss-section"><div class="v2-kicker">Численный прогресс</div>${b.stages.map(s=>{if(s.kind==='unknown')return `<div class="numeric-stage unknown"><div class="stage-line"><b>Неизведанный объём · ${esc(s.name)}</b><span>${Number(s.done||0).toLocaleString('ru-RU')} ${esc(s.unit||'')}</span></div><div class="stage-input"><input type="number" min="0" value="${Number(s.done||0)}" data-boss-stage="${b.id}:${s.id}"></div></div>`;const total=Number(s.total||0),done=Number(s.done||0);return `<div class="numeric-stage"><div class="stage-line"><b>${esc(s.name)}</b><span>${done.toLocaleString('ru-RU')} / ${total.toLocaleString('ru-RU')} ${esc(s.unit||'')}</span></div><div class="bar"><i style="width:${pct(done,total)}%"></i></div><div class="stage-input"><input type="number" min="0" max="${total}" value="${done}" data-boss-stage="${b.id}:${s.id}"></div></div>`}).join('')}</div>`}
  function microHTML(b){if(!(b.microtasks||[]).length)return'';return `<div class="boss-section microtasks-section"><div class="v2-kicker">Микрозадачи</div><div class="microtask-list">${b.microtasks.map(x=>`<label><input type="checkbox" data-microtask-v10="${b.id}:${x.id}" ${x.done?'checked':''} ${b.victoryConfirmed?'disabled':''}><span>${esc(x.label)}</span></label>`).join('')}</div></div>`}
  function finalHTML(b){if(!(b.final||[]).length)return'';return `<div class="boss-section fatality-section"><div class="v2-kicker">Фаталити</div><div class="final-list">${b.final.map(x=>`<label><input type="checkbox" data-final-v10="${b.id}:${x.id}" ${x.done?'checked':''} ${b.victoryConfirmed?'disabled':''}> ${esc(x.label)}</label>`).join('')}</div></div>`}

  function bossCard(b){const rank=b.rank==='epic'?'purple':b.rank,reward=rewardSummary(b),status=b.victoryConfirmed?'Побеждён':victoryReady(b)?'Всё готово к победе':b.deadline?bossThreat(b):'Активен';const rewardBadges=`<div class="boss-currency-reward">${Number(b.rewardGold||0)?`<span>${coinIcon()}<b>${Number(b.rewardGold)}</b></span>`:''}${Number(b.rewardDiamonds||0)?`<span>${diamondIcon()}<b>${Number(b.rewardDiamonds)}</b></span>`:''}</div>`;const action=b.victoryConfirmed?`<div class="boss-victory boss-victory-confirmed"><span>✦</span><b>ПОБЕДА!</b><small>${b.victoryDate?fmt(b.victoryDate):''}${reward?' · '+esc(reward):''}</small></div>`:victoryReady(b)?`<button class="boss-victory-button" data-claim-victory-v10="${b.id}"><span>✦</span><b>ПОБЕДА!</b><small>${reward?'Получить '+esc(reward):'Зафиксировать победу'}</small></button>`:`<div class="victory-locked"><small>Кнопка Победы откроется, когда обязательная работа будет закрыта.</small></div>`;return `<article class="v2-card v2-span-12 boss-card ${rank||''}"><div class="boss-head"><div><div class="v2-kicker">${rankLabel(rank)} босс</div><h2 class="v2-title">${esc(b.title)}</h2>${b.note?`<div class="v2-sub">${esc(b.note)}</div>`:''}</div><div class="boss-actions"><span class="rank">${esc(rankLabel(rank))}</span><button class="soft" data-edit-boss-v10="${b.id}">⚙</button></div></div><div class="boss-meta">${b.deadline?`<span>Дедлайн ${fmt(b.deadline)}</span>`:''}<span>${esc(status)}</span></div>${rewardBadges}${numericHTML(b)}${microHTML(b)}${finalHTML(b)}${b.victoryOutcome?`<div class="victory-outcome"><div class="v2-kicker">После победы</div><p>${esc(b.victoryOutcome)}</p></div>`:''}${b.goldenPrize?`<div class="golden-prize"><div class="v2-kicker">Золотой приз</div><b>★ ${esc(b.goldenPrize)}</b></div>`:''}${action}</article>`}
  bossHTML=bossCard;
  battlesView=function(){return `<div class="v2-wrap"><div class="v2-row battles-title-row"><div><div class="v2-kicker">Арена</div><h1 class="v2-title">Боссы</h1></div><button class="primary" id="addBossV10">＋ Босс</button></div><div class="v2-grid">${state.bosses.map(b=>bossCard(b)).join('')}</div></div>`};

  function makeTasks(text,oldArr){const old=new Map((oldArr||[]).map(x=>[x.label,x]));return String(text||'').split(';').map(x=>x.trim()).filter(Boolean).map(label=>({id:old.get(label)?.id||uid(),label,done:!!old.get(label)?.done}))}
  function bossForm(b={}){const stages=(b.stages||[]).map(s=>`${s.name}|${s.done??0}|${s.total??''}|${s.unit||''}${s.kind==='unknown'?'|unknown':''}`).join('\n'),micro=(b.microtasks||[]).map(x=>x.label).join('; '),finals=(b.final||[]).map(x=>x.label).join('; ');return `<div class="modal-head"><div><div class="v2-kicker">Настройки босса</div><h2>${b.id?'Редактировать':'Добавить босса'}</h2></div><button class="close">×</button></div><form id="bossFormV10"><label>Название<input name="title" required value="${esc(b.title||'')}"></label><div class="form-grid"><label>Ранг<select name="rank">${['gray','green','blue','purple','gold'].map(r=>`<option value="${r}" ${(b.rank==='epic'?'purple':b.rank)===r?'selected':''}>${rankLabel(r)}</option>`).join('')}</select></label><label>Дедлайн<input name="deadline" type="date" value="${b.deadline||''}"></label></div><div class="form-section"><b>Награда за победу</b><div class="form-grid"><label>Золото<input name="rewardGold" type="number" min="0" step="1" value="${Number(b.rewardGold||0)}"></label><label>Алмазы<input name="rewardDiamonds" type="number" min="0" step="1" value="${Number(b.rewardDiamonds||0)}"></label></div></div><label>Золотой приз <small>необязательно; реальная большая награда вне Сокровищницы</small><input name="goldenPrize" value="${esc(b.goldenPrize||'')}" placeholder="например видеокарта / гитара / поездка"></label><label>Что изменится после победы<textarea name="victoryOutcome" placeholder="Что эта победа реально изменит...">${esc(b.victoryOutcome||'')}</textarea></label><label>Численный прогресс <small>каждая строка: название | сделано | всего | единица</small><textarea name="stages" placeholder="Сканирование | 2000 | 28888 | листов">${esc(stages)}</textarea></label><label>Микрозадачи <small>через ; — обычные действия без полос прогресса</small><textarea name="microtasks" placeholder="Сменить обложку; Выложить пост; Ответить рекламщику">${esc(micro)}</textarea></label><label>Фаталити <small>последние обязательные действия перед Победой</small><textarea name="finals">${esc(finals)}</textarea></label><label>Заметка<textarea name="note">${esc(b.note||'')}</textarea></label><div class="modal-actions"><button class="primary">Сохранить</button>${b.id?`<button type="button" class="danger-soft" id="deleteBossV10">Удалить босса</button>`:''}</div></form>`}
  function editBoss(id=null){const b=id?state.bosses.find(x=>x.id===id):null;openModal(bossForm(b||{}));document.querySelector('#bossFormV10').onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget),old=b||{id:uid(),status:'active',victoryConfirmed:false},oldStages=new Map((b?.stages||[]).map(s=>[s.name,s]));const stages=String(f.get('stages')||'').split(/\n+/).map(x=>x.trim()).filter(Boolean).map(line=>{const [name,done,total,unit,kind]=line.split('|').map(x=>x.trim()),prev=oldStages.get(name);return{id:prev?.id||uid(),name,done:Number(done)||0,total:kind==='unknown'||!total?null:Number(total),unit:unit||'',kind:kind==='unknown'?'unknown':'fixed'}});Object.assign(old,{title:f.get('title'),rank:f.get('rank'),deadline:f.get('deadline')||null,rewardGold:Math.max(0,Number(f.get('rewardGold'))||0),rewardDiamonds:Math.max(0,Number(f.get('rewardDiamonds'))||0),goldenPrize:f.get('goldenPrize')||'',victoryOutcome:f.get('victoryOutcome')||'',note:f.get('note')||'',stages,microtasks:makeTasks(f.get('microtasks'),b?.microtasks),final:makeTasks(f.get('finals'),b?.final)});if(!b)state.bosses.push(old);save();document.querySelector('#modal').close();render()};document.querySelector('#deleteBossV10')?.addEventListener('click',()=>{if(confirm('Удалить босса?')){state.bosses=state.bosses.filter(x=>x.id!==b.id);save();document.querySelector('#modal').close();render()}})}

  function victoryModal(b){const g=Number(b.rewardGold||0),d=Number(b.rewardDiamonds||0);openModal(`<div class="victory-modal"><button class="close victory-close">×</button><div class="victory-sigil">✦</div><div class="v2-kicker">${rankLabel(b.rank==='epic'?'purple':b.rank)} босс повержен</div><h2>ПОБЕДА!</h2><h3>${esc(b.title)}</h3>${b.victoryOutcome?`<div class="victory-modal-outcome"><small>Мир изменился:</small><p>${esc(b.victoryOutcome)}</p></div>`:''}<div class="victory-currency"><span>${coinIcon()}<b>+${g}</b><small>золото</small></span><span>${diamondIcon()}<b>+${d}</b><small>алмазы</small></span></div>${b.goldenPrize?`<div class="victory-golden-prize"><small>Золотой приз</small><b>★ ${esc(b.goldenPrize)}</b></div>`:''}<button class="primary victory-confirm" id="confirmVictoryV10">Забрать победу</button></div>`);document.querySelector('#confirmVictoryV10').onclick=()=>{const date=localISO();if(!b.victoryRewardClaimed){state.wallet.gold=Number(state.wallet.gold||0)+g;state.wallet.diamonds=Number(state.wallet.diamonds||0)+d;b.victoryRewardClaimed=true}b.victoryConfirmed=true;b.victoryDate=date;b.status='defeated';const existing=(state.achievements||[]).find(a=>a.bossId===b.id&&a.type==='bossVictory');if(!existing){state.achievements=state.achievements||[];state.achievements.push({id:uid(),date,title:`Победа над боссом: ${b.title}`,tier:b.rank==='gold'?'legendary':'epic',type:'bossVictory',bossId:b.id,note:b.victoryOutcome||'',rewardGold:g,rewardDiamonds:d,goldenPrize:b.goldenPrize||''})}save();document.querySelector('#modal').close();render()}}

  const oldToday=todayView;todayView=function(){let html=oldToday();html=html.replace(/🪙\s*<b>([^<]*)<\/b>/g,`${coinIcon()} <b>$1</b>`).replace(/💎\s*<b>([^<]*)<\/b>/g,`${diamondIcon()} <b>$1</b>`);return html};
  const oldRewards=rewardsView;rewardsView=function(){let html=oldRewards();html=html.replace(/🪙/g,coinIcon()).replace(/💎/g,diamondIcon());return html};

  const oldBind=bind;bind=function(){oldBind();document.querySelector('#addBossV10')?.addEventListener('click',()=>editBoss());document.querySelectorAll('[data-edit-boss-v10]').forEach(btn=>btn.onclick=()=>editBoss(btn.dataset.editBossV10));document.querySelectorAll('[data-microtask-v10]').forEach(input=>input.onchange=()=>{const[bid,tid]=input.dataset.microtaskV10.split(':'),b=state.bosses.find(x=>x.id===bid),t=b?.microtasks.find(x=>x.id===tid);if(t){t.done=input.checked;save();render()}});document.querySelectorAll('[data-final-v10]').forEach(input=>input.onchange=()=>{const[bid,fid]=input.dataset.finalV10.split(':'),b=state.bosses.find(x=>x.id===bid),t=b?.final.find(x=>x.id===fid);if(t){t.done=input.checked;save();render()}});document.querySelectorAll('[data-claim-victory-v10]').forEach(btn=>btn.onclick=()=>{const b=state.bosses.find(x=>x.id===btn.dataset.claimVictoryV10);if(b&&victoryReady(b))victoryModal(b)})};
  render();
})();