// RPG Life v36 — rewards, collapsible ledgers, day memory, checklist practices
(function(){
  state.dayMemories=state.dayMemories||{};
  state.rewardPurchases=state.rewardPurchases||[];
  state.currencyLedger=state.currencyLedger||[];
  state.wallet=state.wallet||{gold:0,diamonds:0};
  (state.practices||[]).forEach(p=>{if(!p.practiceType)p.practiceType='standard';if(!Array.isArray(p.checkItems))p.checkItems=[]});

  const gold36=()=>'<img class="currency-img35 currency-gold35" src="assets/currency-gold.png" alt="золото">';
  const diamond36=()=>'<img class="currency-img35 currency-diamond35" src="assets/currency-diamond.png" alt="алмазы">';
  const currency36=c=>c==='diamonds'?diamond36():gold36();

  function ledgerForDate36(date){return [...(state.currencyLedger||[])].filter(x=>x.date===date).sort((a,b)=>String(b.at||'').localeCompare(String(a.at||'')))}
  function ledgerRows36(rows,withDelete=false){return rows.map(x=>`<div class="ledger-row36"><div><b>${esc(x.title||'Начисление')}</b>${x.note?`<small>${esc(x.note)}</small>`:''}</div><div class="ledger-side36">${Number(x.gold||0)?`${gold36()} <strong>${Number(x.gold)>0?'+':''}${Number(x.gold)}</strong>`:''}${Number(x.diamonds||0)?`${diamond36()} <strong>${Number(x.diamonds)>0?'+':''}${Number(x.diamonds)}</strong>`:''}${withDelete&&x.kind!=='purchase'?`<button data-delete-ledger33="${x.id}" title="Удалить">×</button>`:''}</div></div>`).join('')||'<div class="v2-sub">Начислений нет.</div>'}

  function todayLedger36(){const rows=ledgerForDate36(selectedDate);return `<details class="day-ledger36"><summary><span>${gold36()} Начисления</span><b>${rows.length}</b></summary><div class="day-ledger-body36">${ledgerRows36(rows,false)}</div></details>`}

  const todayBefore36=todayView;
  todayView=function(){
    let html=todayBefore36();
    const needle='<div class="today-log">';
    if(html.includes(needle))html=html.replace(/<div class="today-log">([\s\S]*?)<\/div><\/article>/,m=>m.replace('</article>',todayLedger36()+'</article>'));
    const memory=state.dayMemories[selectedDate]||'';
    const block=`<article class="v2-card v2-span-12 day-memory36"><div class="v2-kicker">Память дня</div><h3 class="v2-title">Чем сегодня запомнился день?</h3><textarea id="dayMemory36" placeholder="Одна короткая вещь, которую хочется оставить в календаре">${esc(memory)}</textarea><div class="day-memory-actions36"><small>${memory?'Сохранено в календаре':'Можно оставить пустым'}</small><button class="soft" id="saveDayMemory36">Сохранить</button></div></article>`;
    return html.replace('</section></div>',block+'</section></div>');
  };

  const yearBefore36=yearView;
  yearView=function(){let html=yearBefore36();const memory=state.dayMemories[selectedDate]||'';if(!memory)return html;return html.replace('</div></div>',`<div class="calendar-memory36"><div class="v2-kicker">Чем запомнился день</div><p>${esc(memory)}</p></div></div></div>`)};

  function rewardEditor36(id=null){
    const r=id?(state.rewards||[]).find(x=>x.id===id):null;
    openModal(`<div class="modal-head"><div><div class="v2-kicker">Сокровищница</div><h2>${r?'Изменить награду':'Новая награда'}</h2></div><button class="close">×</button></div><form id="rewardForm36"><label>Название<input name="title" required value="${esc(r?.title||'')}"></label><div class="form-grid"><label>Валюта<select name="currency"><option value="gold" ${r?.currency!=='diamonds'?'selected':''}>Золото</option><option value="diamonds" ${r?.currency==='diamonds'?'selected':''}>Алмазы</option></select></label><label>Цена<input name="price" type="number" min="0" step="1" required value="${Number(r?.price||0)}"></label></div><label>Комментарий<input name="note" value="${esc(r?.note||'')}"></label><div class="modal-actions"><button class="primary">Сохранить</button>${r?'<button type="button" class="danger-soft" id="deleteReward36">Удалить</button>':''}</div></form>`);
    document.querySelector('#rewardForm36').onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget),target=r||{id:uid()};Object.assign(target,{title:String(f.get('title')||'').trim(),currency:f.get('currency')==='diamonds'?'diamonds':'gold',price:Math.max(0,Math.round(Number(f.get('price'))||0)),note:String(f.get('note')||'').trim()});if(!r)state.rewards.push(target);save();document.querySelector('#modal').close();render()};
    document.querySelector('#deleteReward36')?.addEventListener('click',()=>{if(confirm('Удалить награду из Сокровищницы?')){state.rewards=state.rewards.filter(x=>x.id!==r.id);save();document.querySelector('#modal').close();render()}});
  }

  function buyReward36(id){
    const r=(state.rewards||[]).find(x=>x.id===id);if(!r)return;
    const price=Math.max(0,Number(r.price||0)),cur=r.currency==='diamonds'?'diamonds':'gold',have=Number(state.wallet[cur]||0);
    if(have<price){toast(`Не хватает ${cur==='gold'?'золота':'алмазов'}`);return}
    if(!confirm(`Купить «${r.title}» за ${price} ${cur==='gold'?'золота':'алмазов'}?`))return;
    state.wallet[cur]=Math.max(0,have-price);
    const row={id:uid(),rewardId:r.id,title:r.title,currency:cur,price,date:today(),at:new Date().toISOString()};state.rewardPurchases.push(row);
    state.currencyLedger.push({id:uid(),ledgerKey:`purchase:${row.id}`,date:row.date,at:row.at,kind:'purchase',sourceId:r.id,title:`Покупка · ${r.title}`,gold:cur==='gold'?-price:0,diamonds:cur==='diamonds'?-price:0});
    save();render();toast('Награда куплена ✦');
  }

  rewardsView=function(){
    const ledger=[...(state.currencyLedger||[])].sort((a,b)=>String(b.at||b.date||'').localeCompare(String(a.at||a.date||''))).slice(0,80);
    return `<div class="v2-wrap"><div class="v2-row"><div><div class="v2-kicker">Сокровищница</div><h1 class="v2-title">Награды</h1></div><button class="primary" id="addReward36">＋ Награда</button></div><section class="treasury-wallet treasury-wallet32"><div><h2>На руках</h2></div><div class="treasury-wallet-values"><div>${gold36()}<span><b>${Number(state.wallet.gold||0).toLocaleString('ru-RU')}</b><small>золото</small></span></div><div>${diamond36()}<span><b>${Number(state.wallet.diamonds||0).toLocaleString('ru-RU')}</b><small>алмазы</small></span></div></div></section><div class="reward-grid reward-grid36">${(state.rewards||[]).map(r=>`<article class="reward reward36"><div><b>${esc(r.title)}</b>${r.note?`<small>${esc(r.note)}</small>`:''}</div><strong>${currency36(r.currency)} ${Number(r.price||0)}</strong><div class="reward-actions36"><button class="primary" data-buy-reward36="${r.id}">Купить</button><button class="soft" data-edit-reward36="${r.id}">✎</button></div></article>`).join('')||'<div class="v2-card empty-v2">Наград пока нет.</div>'}</div><details class="v2-card treasury-ledger36"><summary><span>${gold36()} История начислений и покупок</span><b>${ledger.length}</b></summary><div class="treasury-ledger-body36">${ledgerRows36(ledger,true)}</div></details></div>`;
  };

  const resourceMeta36={inspiration:'Вдохновение',calm:'Спокойствие',energy:'Энергия',recognition:'Узнавание'};
  function variantsText36(p){return (p.variants||[]).map(v=>`${v.name}|${v.kcal||0}`).join('; ')}
  function practiceForm36(p={},primaryBranch='health'){
    const branches=p.branches||{[primaryBranch]:10},r=p.rhythm||{type:'timesWeek',value:1},fx=p.resourceEffects||{},type=p.practiceType||'standard';
    return `<div class="modal-head"><div><div class="v2-kicker">Настройки практики</div><h2>${p.id?'Изменить':'Добавить'}</h2></div><button class="close">×</button></div><form id="practiceFormV36"><label>Название<input name="name" required value="${esc(p.name||'')}"></label><label>Тип практики<select name="practiceType"><option value="standard" ${type!=='checklist'?'selected':''}>Обычная</option><option value="checklist" ${type==='checklist'?'selected':''}>Составная · галочки</option></select></label><label class="check-items-setting36">Пункты составной практики<input name="checkItems" value="${esc((p.checkItems||[]).join('; '))}" placeholder="Витамин D; Клетчатка; Магний; Омега-3"></label><div class="form-section"><b>Награда за выполнение</b><label>${gold36()} Золото<input name="rewardGold" type="number" min="0" step="1" value="${Math.max(0,Number(p.rewardGold||0))}"></label></div><div class="form-section"><b>Влияние на ветки</b>${Object.entries(practiceBranches).map(([k,m])=>`<div class="weight-row"><span>${m.icon} ${m.name}</span><input type="number" min="0" max="100" name="weight_${k}" value="${branches[k]||0}"></div>`).join('')}</div><div class="form-section"><b>Влияние на ресурсы</b>${Object.entries(resourceMeta36).map(([k,m])=>`<div class="weight-row"><span>${m}</span><input type="number" min="-20" max="20" name="resource_${k}" value="${Number(fx[k]||0)}"></div>`).join('')}</div><label>Эффект действует, дней<input name="resourceEffectDays" type="number" min="1" max="365" value="${Math.max(1,Number(p.resourceEffectDays||1))}"></label><label>Желательный ритм<select name="rhythmType"><option value="timesWeek" ${r.type==='timesWeek'?'selected':''}>N раз в неделю</option><option value="weeklyAmount" ${r.type==='weeklyAmount'?'selected':''}>Количество за неделю</option><option value="daily" ${r.type==='daily'?'selected':''}>Ежедневно</option><option value="everyDays" ${r.type==='everyDays'?'selected':''}>Раз в N дней</option><option value="soft" ${r.type==='soft'?'selected':''}>Без жёсткой частоты</option></select></label><div class="form-grid"><label>Число<input name="rhythmValue" type="number" min="0" value="${r.value??''}"></label><label>Единица<input name="unit" value="${esc(r.unit||'')}"></label></div><label>Показатели<input name="metrics" value="${esc((p.metrics||[]).join('; '))}"></label><label>Варианты дневной записи и расход<input name="variants" value="${esc(variantsText36(p))}"></label><label class="quiet-practice-toggle"><input type="checkbox" name="hideFromTimeline" ${p.hideFromTimeline?'checked':''}><span><b>Не отмечать в глобальном календаре и неделе</b></span></label><div class="modal-actions"><button class="primary">Сохранить</button>${p.id?`<button type="button" class="danger-soft" id="deletePractice36">Удалить</button>`:''}</div></form>`;
  }

  openPracticeEditor=function(id,branch){const p=id?state.practices.find(x=>x.id===id):null;openModal(practiceForm36(p||{},branch));const form=document.querySelector('#practiceFormV36');form.onsubmit=e=>{e.preventDefault();const f=new FormData(form),target=p||{id:uid()},branches={},resourceEffects={};Object.keys(practiceBranches).forEach(k=>{const v=Number(f.get('weight_'+k))||0;if(v>0)branches[k]=clamp(v)});Object.keys(resourceMeta36).forEach(k=>{const v=Math.max(-20,Math.min(20,Math.round(Number(f.get('resource_'+k))||0)));if(v)resourceEffects[k]=v});const rt=f.get('rhythmType'),val=Number(f.get('rhythmValue'))||null,rhythm={type:rt};if(['timesWeek','everyDays'].includes(rt))rhythm.value=val||1;if(rt==='weeklyAmount'){rhythm.value=val||1;rhythm.unit=f.get('unit')||'ед.'}const split=v=>String(v||'').split(/[;,]/).map(x=>x.trim()).filter(Boolean);const variants=split(f.get('variants')).map(x=>{const [name,kcal]=x.split('|');return{name:name.trim(),kcal:Number(kcal)||0}});Object.assign(target,{name:String(f.get('name')||'').trim(),practiceType:f.get('practiceType')==='checklist'?'checklist':'standard',checkItems:split(f.get('checkItems')),rewardGold:Math.max(0,Math.round(Number(f.get('rewardGold'))||0)),branches,rhythm,metrics:split(f.get('metrics')),variants,resourceEffects,resourceEffectDays:Math.max(1,Math.min(365,Number(f.get('resourceEffectDays'))||1)),hideFromTimeline:f.get('hideFromTimeline')==='on'});if(!p)state.practices.push(target);save();document.querySelector('#modal').close();render()};document.querySelector('#deletePractice36')?.addEventListener('click',()=>{if(confirm('Удалить практику? Старые записи останутся в истории.')){state.practices=state.practices.filter(x=>x.id!==p.id);save();document.querySelector('#modal').close();render()}})};

  const standardLog36=logPractice;
  logPractice=function(id,logId=null){const p=state.practices.find(x=>x.id===id);if(!p||p.practiceType!=='checklist')return standardLog36(id,logId);const existing=logId?state.practiceLogs.find(x=>x.id===logId):null;openModal(`<div class="modal-head"><div><div class="v2-kicker">${fmt(selectedDate)}</div><h2>${esc(p.name)}</h2>${Number(p.rewardGold||0)?`<div class="practice-log-reward">За выполнение: ${gold36()} <b>${Number(p.rewardGold)}</b></div>`:''}</div><button class="close">×</button></div><form id="checkPracticeForm36"><fieldset class="option-field checklist-practice36"><legend>Что сделано?</legend><div class="option-grid">${(p.checkItems||[]).map(item=>`<label><input type="checkbox" name="check" value="${esc(item)}" ${(existing?.checks||[]).includes(item)?'checked':''}><span>${esc(item)}</span></label>`).join('')}</div></fieldset><label>Заметка<input name="note" value="${esc(existing?.note||'')}"></label><button class="primary">Сохранить</button></form>`);document.querySelector('#checkPracticeForm36').onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget),checks=f.getAll('check'),data={practiceId:id,date:selectedDate,metrics:{},options:[],checks,note:f.get('note')||'',kcal:0,amount:null};if(existing){Object.assign(existing,data)}else{const reward=Math.max(0,Math.round(Number(p.rewardGold||0))),row={id:uid(),...data,rewardGoldGranted:reward};state.practiceLogs.push(row);if(reward)state.wallet.gold=Number(state.wallet.gold||0)+reward;if(reward)state.currencyLedger.push({id:uid(),ledgerKey:`practice:${row.id}`,date:row.date,at:new Date().toISOString(),kind:'practice',sourceId:id,sourceLogId:row.id,title:`Практика · ${p.name}`,gold:reward,diamonds:0})}save();document.querySelector('#modal').close();render()}};

  const logDetailsBefore36=logDetails;
  logDetails=function(l){if(Array.isArray(l.checks)&&l.checks.length){const p=state.practices.find(x=>x.id===l.practiceId),all=p?.checkItems?.length||l.checks.length;return `${l.checks.join(', ')} · ${l.checks.length}/${all}${l.note?` · ${l.note}`:''}`}return logDetailsBefore36(l)};

  const bindBefore36=bind;
  bind=function(){bindBefore36();document.querySelector('#addReward36')?.addEventListener('click',()=>rewardEditor36());document.querySelectorAll('[data-edit-reward36]').forEach(b=>b.onclick=()=>rewardEditor36(b.dataset.editReward36));document.querySelectorAll('[data-buy-reward36]').forEach(b=>b.onclick=()=>buyReward36(b.dataset.buyReward36));document.querySelector('#saveDayMemory36')?.addEventListener('click',()=>{const v=String(document.querySelector('#dayMemory36')?.value||'').trim();if(v)state.dayMemories[selectedDate]=v;else delete state.dayMemories[selectedDate];save();render();toast('День сохранён в памяти')})};

  save();render();
})();