// RPG Life v32 — visible currency, auditable corrections, sleeping bosses, Gryzliki and quick boss hits
(function(){
  state.wallet=state.wallet||{gold:0,diamonds:0};
  state.currencyLedger=state.currencyLedger||[];
  state.bosses=state.bosses||[];
  state.gryzliki=state.gryzliki||[];
  state.bosses.forEach(b=>{if(!b.status)b.status='active'});

  const coin32=()=>'<span class="currency-symbol32 gold32" aria-label="золото">🪙</span>';
  const gem32=()=>'<span class="currency-symbol32 diamond32" aria-label="алмазы">💎</span>';
  const fmtMoney32=n=>Number(n||0).toLocaleString('ru-RU');
  const rankLabel32=r=>({gray:'Серый',green:'Зелёный',blue:'Синий',purple:'Фиолетовый',gold:'Золотой',epic:'Фиолетовый'})[r]||r||'Без ранга';

  function currencyHistory32(){
    const rows=[...(state.currencyLedger||[])].sort((a,b)=>String(b.at||b.date||'').localeCompare(String(a.at||a.date||''))).slice(0,40);
    return `<div class="ledger32">${rows.map(x=>`<div class="ledger-row32"><span><b>${esc(x.title||'Начисление')}</b><small>${x.date?fmt(x.date):''}${x.note?` · ${esc(x.note)}`:''}</small></span><span class="ledger-values32">${Number(x.gold||0)?`${coin32()} <b>${Number(x.gold)>0?'+':''}${Number(x.gold)}</b>`:''}${Number(x.diamonds||0)?`${gem32()} <b>${Number(x.diamonds)>0?'+':''}${Number(x.diamonds)}</b>`:''}</span></div>`).join('')||'<div class="v2-sub">История пока пуста.</div>'}</div>`;
  }

  function correction32(){
    openModal(`<div class="modal-head"><div><div class="v2-kicker">Экономика</div><h2>Исправить баланс</h2></div><button class="close">×</button></div><form id="currencyCorrection32"><div class="form-grid"><label>${coin32()} Золото<input name="gold" type="number" step="1" value="0" placeholder="-20 или 20"></label><label>${gem32()} Алмазы<input name="diamonds" type="number" step="1" value="0" placeholder="-1 или 1"></label></div><label>Почему<input name="note" required placeholder="лишнее начисление за баф"></label><small>Исправление не стирает старую запись: в истории остаётся и начисление, и корректировка.</small><button class="primary">Применить</button></form>`);
    document.querySelector('#currencyCorrection32').onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget),gold=Math.round(Number(f.get('gold'))||0),diamonds=Math.round(Number(f.get('diamonds'))||0),note=String(f.get('note')||'').trim();if(!gold&&!diamonds)return;state.wallet.gold=Math.max(0,Number(state.wallet.gold||0)+gold);state.wallet.diamonds=Math.max(0,Number(state.wallet.diamonds||0)+diamonds);state.currencyLedger.push({id:uid(),ledgerKey:`adjustment:${uid()}`,date:today(),at:new Date().toISOString(),kind:'adjustment',sourceId:'manual',title:'Корректировка баланса',note,gold,diamonds});save();document.querySelector('#modal').close();render()};
  }

  rewardsView=function(){
    return `<div class="v2-wrap"><div class="v2-row"><div><div class="v2-kicker">Сокровищница</div><h1 class="v2-title">Награды</h1></div><button class="soft" id="correctCurrency32">± баланс</button></div><section class="treasury-wallet treasury-wallet32"><div><h2>На руках</h2></div><div class="treasury-wallet-values"><div>${coin32()}<span><b>${fmtMoney32(state.wallet.gold)}</b><small>золото</small></span></div><div>${gem32()}<span><b>${fmtMoney32(state.wallet.diamonds)}</b><small>алмазы</small></span></div></div></section><div class="v2-card"><div class="reward-grid">${(state.rewards||[]).map(r=>`<div class="reward"><b>${esc(r.title)}</b><span>${r.currency==='gold'?coin32():gem32()} ${r.price}</span></div>`).join('')}</div></div><article class="v2-card ledger-card32"><div class="v2-row"><div><div class="v2-kicker">Экономика</div><h3 class="v2-title">История начислений</h3></div><button class="soft" id="correctCurrency32b">± исправить</button></div>${currencyHistory32()}</article></div>`;
  };

  function activeBosses32(){return state.bosses.filter(b=>!b.victoryConfirmed&&b.status!=='sleeping')}
  function sleepingBosses32(){return state.bosses.filter(b=>!b.victoryConfirmed&&b.status==='sleeping')}
  function defeatedBosses32(){return state.bosses.filter(b=>b.victoryConfirmed)}
  function bossPortrait32(b){return b.imageData?`<img class="boss-portrait" src="${b.imageData}" alt="">`:'<div class="boss-portrait boss-portrait-empty">⚔</div>'}
  function pct32(a,b){return b?Math.max(0,Math.min(100,Number(a||0)/Number(b)*100)):0}
  function victoryReady32(b){const stages=(b.stages||[]).every(s=>s.total===null||Number(s.done||0)>=Number(s.total||0)),micro=!(b.microtasks||[]).length||(b.microtasks||[]).every(x=>x.done),fin=!(b.final||[]).length||(b.final||[]).every(x=>x.done),work=(b.stages||[]).length||(b.microtasks||[]).length||(b.final||[]).length;return !!work&&stages&&micro&&fin&&!b.victoryConfirmed}

  function bossProgress32(b){return `<div class="boss-section"><div class="v2-kicker">Численный прогресс</div>${(b.stages||[]).map(s=>{const done=Number(s.done||0),total=s.total===null?null:Number(s.total||0);return `<div class="boss-progress-row22"><div class="boss-progress-head22"><b>${esc(s.name)}</b><span>${done.toLocaleString('ru-RU')}${total===null?'':` / ${total.toLocaleString('ru-RU')}`} ${esc(s.unit||'')}</span></div>${total!==null?`<div class="bar"><i style="width:${pct32(done,total)}%"></i></div>`:''}<div class="boss-hit32"><button class="soft" data-hit32="${b.id}:${s.id}">＋ добавить сделанное</button><button class="ghost" data-set32="${b.id}:${s.id}">✎ итог</button></div></div>`}).join('')}</div>`}
  function checks32(title,arr,attr,b){if(!(arr||[]).length)return'';const done=arr.filter(x=>x.done).length;return `<details class="boss-collapse22"><summary>${title}<span>${done}/${arr.length} ▾</span></summary><div class="microtask-list">${arr.map(x=>`<label><input type="checkbox" ${attr}="${b.id}:${x.id}" ${x.done?'checked':''}><span>${esc(x.label)}</span></label>`).join('')}</div></details>`}
  function bossCard32(b){const rank=b.rank==='epic'?'purple':b.rank,ready=victoryReady32(b),rew=[];if(Number(b.rewardGold||0))rew.push(`${coin32()} ${Number(b.rewardGold)}`);if(Number(b.rewardDiamonds||0))rew.push(`${gem32()} ${Number(b.rewardDiamonds)}`);return `<article class="v2-card boss-card boss-card22 ${rank||''}"><div class="boss-title-line">${bossPortrait32(b)}<div class="boss-title-copy"><div class="v2-kicker">${rankLabel32(rank)} босс</div><h2 class="v2-title">${esc(b.title)}</h2>${b.note?`<div class="v2-sub">${esc(b.note)}</div>`:''}</div><div class="boss-actions"><button class="soft" data-sleep32="${b.id}">💤 усыпить</button><button class="soft" data-edit-v12="${b.id}">⚙</button></div></div><div class="boss-meta">${b.deadline?`<span>Дедлайн ${fmt(b.deadline)}</span>`:''}<span>На арене</span>${rew.length?`<span>${rew.join(' · ')}</span>`:''}</div>${bossProgress32(b)}${checks32('Микрозадачи',b.microtasks,'data-micro-v12',b)}${checks32('Фаталити',b.final,'data-final-v12',b)}${ready?`<button class="boss-victory-button" data-win-v12="${b.id}"><span>✦</span><b>ПОБЕДА!</b><small>Получить награду</small></button>`:''}</article>`}
  function sleeping32(b){return `<div class="sleeping-boss32">${bossPortrait32(b)}<span><b>💤 ${esc(b.title)}</b><small>${b.deadline?`Дедлайн ${fmt(b.deadline)} · `:''}${rankLabel32(b.rank==='epic'?'purple':b.rank)}</small></span><button class="soft" data-wake32="${b.id}">Разбудить</button></div>`}
  function defeated32(b){return `<div class="sleeping-boss32 defeated32">${bossPortrait32(b)}<span><b>${esc(b.title)}</b><small>${b.victoryDate?`Победа ${fmt(b.victoryDate)}`:'Побеждён'}</small></span></div>`}

  function gryzlikCard32(g){return `<div class="gryzlik32 ${g.done?'done':''}"><label><input type="checkbox" data-gryzlik-done32="${g.id}" ${g.done?'checked':''}><span><b>🦷 ${esc(g.title)}</b>${g.note?`<small>${esc(g.note)}</small>`:''}</span></label><button data-gryzlik-del32="${g.id}">×</button></div>`}
  function addGryzlik32(){openModal(`<div class="modal-head"><div><div class="v2-kicker">Мелкая нечисть</div><h2>Новый Грызлик</h2></div><button class="close">×</button></div><form id="gryzlikForm32"><label>Что грызёт?<input name="title" required placeholder="Дослать акт"></label><label>Комментарий<input name="note" placeholder="неприятно, но на 20 минут"></label><button class="primary">Выпустить Грызлика</button></form>`);document.querySelector('#gryzlikForm32').onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget);state.gryzliki.push({id:uid(),title:String(f.get('title')||'').trim(),note:String(f.get('note')||'').trim(),done:false,createdAt:new Date().toISOString()});save();document.querySelector('#modal').close();render()}}

  battlesView=function(){const active=activeBosses32(),sleep=sleepingBosses32(),dead=defeatedBosses32(),gryz=(state.gryzliki||[]).filter(g=>!g.done),grdead=(state.gryzliki||[]).filter(g=>g.done);return `<div class="v2-wrap"><div class="v2-row battles-title-row"><div><div class="v2-kicker">Арена</div><h1 class="v2-title">Боссы</h1><div class="v2-sub">На арене максимум 3. Остальные могут спать.</div></div><button class="primary" id="addBossV12">＋ Босс</button></div>${active.length?`<div class="arena-active-grid22">${active.map(bossCard32).join('')}</div>`:'<div class="v2-card empty-v2">Арена свободна.</div>'}${sleep.length?`<article class="v2-card sleeping-section32"><div class="v2-kicker">Спящие боссы</div><h2>💤 Пока не трогаем</h2><div>${sleep.map(sleeping32).join('')}</div></article>`:''}<article class="v2-card gryz-section32"><div class="v2-row"><div><div class="v2-kicker">Мелкая нечисть</div><h2>Грызлики</h2><div class="v2-sub">Мелкие противные дела. Их может быть сколько угодно.</div></div><button class="primary" id="addGryzlik32">＋ Грызлик</button></div><div class="gryz-list32">${gryz.map(gryzlikCard32).join('')||'<div class="v2-sub">Никто сейчас не грызёт.</div>'}</div>${grdead.length?`<details><summary>Прибитые Грызлики · ${grdead.length}</summary><div class="gryz-list32">${grdead.slice(-20).reverse().map(gryzlikCard32).join('')}</div></details>`:''}</article>${dead.length?`<article class="v2-card sleeping-section32"><div class="v2-kicker">История побед</div><h2>Побеждённые</h2><div>${dead.map(defeated32).join('')}</div></article>`:''}</div>`};
  bossHTML=bossCard32;

  function hitStage32(token){const [bid,sid]=token.split(':'),b=state.bosses.find(x=>x.id===bid),s=b?.stages?.find(x=>x.id===sid);if(!s)return;openModal(`<div class="modal-head"><div><div class="v2-kicker">Удар по боссу</div><h2>${esc(s.name)}</h2></div><button class="close">×</button></div><form id="hitStageForm32"><label>Сколько сделано сейчас<input name="delta" type="number" min="0" required autofocus></label><small>Было: ${Number(s.done||0).toLocaleString('ru-RU')} ${esc(s.unit||'')}${s.total!==null?` · всего ${Number(s.total).toLocaleString('ru-RU')}`:''}</small><button class="primary">Добавить к прогрессу</button></form>`);document.querySelector('#hitStageForm32').onsubmit=e=>{e.preventDefault();const add=Math.max(0,Number(new FormData(e.currentTarget).get('delta'))||0),next=Number(s.done||0)+add;s.done=s.total===null?next:Math.min(Number(s.total),next);save();document.querySelector('#modal').close();render()}}
  function setStage32(token){const [bid,sid]=token.split(':'),b=state.bosses.find(x=>x.id===bid),s=b?.stages?.find(x=>x.id===sid);if(!s)return;openModal(`<div class="modal-head"><h2>${esc(s.name)}</h2><button class="close">×</button></div><form id="setStageForm32"><label>Итог сделано<input name="done" type="number" min="0" value="${Number(s.done||0)}"></label><button class="primary">Сохранить</button></form>`);document.querySelector('#setStageForm32').onsubmit=e=>{e.preventDefault();const n=Math.max(0,Number(new FormData(e.currentTarget).get('done'))||0);s.done=s.total===null?n:Math.min(Number(s.total),n);save();document.querySelector('#modal').close();render()}}

  function sleepBoss32(id){const b=state.bosses.find(x=>x.id===id);if(!b)return;b.status='sleeping';save();render()}
  function wakeBoss32(id){const b=state.bosses.find(x=>x.id===id);if(!b)return;if(activeBosses32().length>=3){toast('На арене уже три босса. Сначала усыпи кого-нибудь 😈');return}b.status='active';save();render()}

  const bindBefore32=bind;
  bind=function(){bindBefore32();document.querySelector('#correctCurrency32')?.addEventListener('click',correction32);document.querySelector('#correctCurrency32b')?.addEventListener('click',correction32);document.querySelector('#addGryzlik32')?.addEventListener('click',addGryzlik32);document.querySelectorAll('[data-hit32]').forEach(x=>x.onclick=()=>hitStage32(x.dataset.hit32));document.querySelectorAll('[data-set32]').forEach(x=>x.onclick=()=>setStage32(x.dataset.set32));document.querySelectorAll('[data-sleep32]').forEach(x=>x.onclick=()=>sleepBoss32(x.dataset.sleep32));document.querySelectorAll('[data-wake32]').forEach(x=>x.onclick=()=>wakeBoss32(x.dataset.wake32));document.querySelectorAll('[data-gryzlik-done32]').forEach(x=>x.onchange=()=>{const g=state.gryzliki.find(v=>v.id===x.dataset.gryzlikDone32);if(g){g.done=x.checked;g.doneAt=x.checked?new Date().toISOString():null;save();render()}});document.querySelectorAll('[data-gryzlik-del32]').forEach(x=>x.onclick=()=>{state.gryzliki=state.gryzliki.filter(g=>g.id!==x.dataset.gryzlikDel32);save();render()})};

  // If old data already has more than three live bosses, keep first three awake and put the rest to sleep.
  const live=state.bosses.filter(b=>!b.victoryConfirmed&&b.status!=='sleeping');
  if(live.length>3){live.slice(3).forEach(b=>b.status='sleeping');save()}
  render();
})();
